package org.labor.pojos;

// Generated Jul 25, 2013 11:50:54 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "Employee")
public class Employee implements java.io.Serializable {

	private Integer employeeId;
	private String name;
	private String email;
	private String phone;
	private Set employeeToJobs = new HashSet(0);

	public Employee() {
	}

	public Employee(String name, String email, String phone, Set employeeToJobs) {
		this.name = name;
		this.email = email;
		this.phone = phone;
		this.employeeToJobs = employeeToJobs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "employee_id", unique = true, nullable = false)
	public Integer getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(Integer employeeId) {
		this.employeeId = employeeId;
	}

	@Column(name = "name", length = 4096)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email", length = 4096)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone", length = 4096)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee")
	public Set getEmployeeToJobs() {
		return this.employeeToJobs;
	}

	public void setEmployeeToJobs(Set employeeToJobs) {
		this.employeeToJobs = employeeToJobs;
	}

}
