package org.labor.pojos;

// Generated Jul 25, 2013 11:50:54 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Job generated by hbm2java
 */
@Entity
@Table(name = "Job")
public class Job implements java.io.Serializable {

	private Integer jobId;
	private Date beginTime;
	private Date endTime;
	private String description;
	private String perks;
	private String location;
	private Float fee;
	private Integer employerId;
	private Set employerToJobs = new HashSet(0);
	private Set employeeToJobs = new HashSet(0);

	public Job() {
	}

	public Job(Date beginTime, Date endTime) {
		this.beginTime = beginTime;
		this.endTime = endTime;
	}

	public Job(Date beginTime, Date endTime, String description, String perks,
			String location, Float fee, Integer employerId, Set employerToJobs,
			Set employeeToJobs) {
		this.beginTime = beginTime;
		this.endTime = endTime;
		this.description = description;
		this.perks = perks;
		this.location = location;
		this.fee = fee;
		this.employerId = employerId;
		this.employerToJobs = employerToJobs;
		this.employeeToJobs = employeeToJobs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "job_id", unique = true, nullable = false)
	public Integer getJobId() {
		return this.jobId;
	}

	public void setJobId(Integer jobId) {
		this.jobId = jobId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "begin_time", nullable = false, length = 0)
	public Date getBeginTime() {
		return this.beginTime;
	}

	public void setBeginTime(Date beginTime) {
		this.beginTime = beginTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_time", nullable = false, length = 0)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Column(name = "description", length = 4096)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "perks", length = 4096)
	public String getPerks() {
		return this.perks;
	}

	public void setPerks(String perks) {
		this.perks = perks;
	}

	@Column(name = "location", length = 4096)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "fee", precision = 12, scale = 0)
	public Float getFee() {
		return this.fee;
	}

	public void setFee(Float fee) {
		this.fee = fee;
	}

	@Column(name = "employer_id")
	public Integer getEmployerId() {
		return this.employerId;
	}

	public void setEmployerId(Integer employerId) {
		this.employerId = employerId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "job")
	public Set getEmployerToJobs() {
		return this.employerToJobs;
	}

	public void setEmployerToJobs(Set employerToJobs) {
		this.employerToJobs = employerToJobs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "job")
	public Set getEmployeeToJobs() {
		return this.employeeToJobs;
	}

	public void setEmployeeToJobs(Set employeeToJobs) {
		this.employeeToJobs = employeeToJobs;
	}

}
